### PR TITLE
Main blockly tooltip and support for Item mod element

### PR DESCRIPTION
**Pull request by NOYBss**
**In this PR**
- Renamed a lot of Item panels to better reflect what they are
- Added main blockly tooltip stuff
- Added blockly tooltip support for Item mod element

I have some other things in my mind but this pr is already 40 files 
so I'll add some more advanced stuff (text style, color, etc.) in other prs

### CODE REVIEW

**Comment by Max094Reikeb** [comment]
Not a fan of it, and externalization key creation is not automatic so...

**Comment by NOYBss** [comment]
Converting the pr to draft:
1) Found a little bug
2) Will try to automate translation key creation for translatable tooltips

**Comment by NOYBss** [comment]
Translatable text key creation is now automatic, and everything should be good to go now

**Comment by NOYBss** [comment]
uhh why is GitHub's resolve conflict option always causes problems
I just added another procedure coverage label to generator selector, and github detects it as I rewrote the whole file

**Pull request merged**
