### PR TITLE
UI Update

### PR DESCRIPTION
**Pull request by Max094Reikeb**
This PR is the official UI Update. Big thanks to @willpill!
Changelog: 
- Modified a lot of icons
- Modified splash screen background

NOTE: This PR merges the branch `ui-update` into branch `master`. It will be merge when the UI update will be ready (with the new UI complete in branch `ui-update`

### CODE REVIEW

**Comment by Goldorion** [comment]
It only changes icons and the splash screen. It doesn't change the UI (the main menu and the UI of workspaces).

**Comment by ShockingArtist** [comment]
pre #111

**Comment by willpill** [comment]
injecttag
Inject Tag Icon, requested by @Max094Reikeb , way easier than I thought.

**Comment by willpill** [comment]
Thanks for committing the icon

**Comment by willpill** [comment]
First to note that these icons are just for reference and as you start working on the UI update it will be re-made. 
Now that I think about it the icons that are committed to the UI-update branch, some of them are poorly scaled and are having problems being viewed on smaller devices. It is also worth noting that some of the icons are un-recognizable when scaled to a certain extent. That is why I would recommend using codicons as a substitute, and they are effortless to use.

- Download it here https://github.com/microsoft/vscode-codicons/blob/master/dist/codicon.ttf as a font
- Attribute its license (https://creativecommons.org/licenses/by/4.0/) with https://github.com/microsoft/vscode-codicons/blob/master/LICENSE

**Pull request closed without merging**
