### PR TITLE
Tree mod element

### PR DESCRIPTION
**Pull request by Goldorion**
This PR adds a Tree mod element. No converter has been made as it's pretty hard to move values to a brand new mod element. Vines and fruits have been removed as this element now uses the new (basic) code introduced in 1.15.2.
(Saplings are not included.)

### CODE REVIEW

**Comment by CrispyChips6660** [comment]
I don't think this should be merged, since it would be hard to convert current trees and there is no support for vines and fruit

**Comment by Blackout03** [comment]
I disagree with what Crispy said, Also Travis CI build failed

**Comment by Goldorion** [comment]
> 
> 
> I disagree with what Crispy said, Also Travis CI build failed

I know. I'm waiting that Klemen merges the new tree selector to complete the feature.

**Comment by CrispyChips6660** [comment]
> I disagree with what Crispy said
Why? retrocompatibility is always important..

**Comment by Goldorion** [comment]
> 
> 
> > I disagree with what Crispy said
> Why? retro compatibility is always important.
It's possible to make a converter to transfer the current custom tree to a new tree mod element, but it's just harder than a normal converter. I will try to make one later.

**Comment by Max094Reikeb** [comment]
Why did you close this?

**Pull request closed without merging**
