### PR TITLE
Building tool pack maker

### LINKED ISSUE #171: Building pack creator
**Describe the feature**

A quick way how to add equivalent of blocks like, stairs and slabs

**How would you implement it?**

It would be new creation pack.

You would select block mod element which will be the base and would copy all basic things from it like hardness and texture.

You would then have checklist with which blocks you want to create, it would include:
Stairs, slabs, walls, fence, fence gates, door, trapdoor, button, presure plates and etc.

You could also choose to generate recipes and you could also choose to generate additional stone cutter recipes.

This would save a lot of time and a lot of mental health. Thanks a lot

### PR DESCRIPTION
**Pull request by Goldorion**
This PR adds a new building pack maker. Closes #171 

Changelog:
* This new pack maker can generate a basic block, stairs, slab, wall, fence, fence gate, trapdoor, door, button and pressure plate blocks. 
* If the basic block is selected, recipes will be generated too based on this basic block. 
* Stonecutter recipes have also been added for useful blocks.
* Some new recipe templates in RecipeUtils have been added (they are not implemented for the custom pack makers).
* The wood pack icon is now used for this new pack maker. 
Note: The wood pack maker now doesn't have an icon as this new tool is better. It's still in the core and we can still use it.

### CODE REVIEW

**Comment by Max094Reikeb** [comment]
Isn't there a way to check if the pack is a wood pack? It could add the log, wood/planks, and fences tag to the blocks.

**Comment by Goldorion** [comment]
> 
> 
> Isn't there a way to check if the pack is a wood pack? It could add the log, wood/planks, and fences tag to the blocks.

Do you mean like be able to choose if it will generate a wood pack or a stone pack?

**Comment by Max094Reikeb** [comment]
> > Isn't there a way to check if the pack is a wood pack? It could add the log, wood/planks, and fences tag to the blocks.
> 
> Do you mean like be able to choose if it will generate a wood pack or a stone pack?

Yes. And if we check wood pack, it generates and adds all tags listed above.

**Comment by Goldorion** [comment]
> 
> 
> > > Isn't there a way to check if the pack is a wood pack? It could add the log, wood/planks, and fences tag to the blocks.
> > 
> > 
> > Do you mean like be able to choose if it will generate a wood pack or a stone pack?
> 
> Yes. And if we check wood pack, it generates and adds all tags listed above.

I can try to add this option.

**Comment by Goldorion** [comment]
Concerning the option to select between a wood pack maker and this current pack, I will add it, but not for the moment. I will make another PR in the future.

**Review by Max094Reikeb — CHANGES_REQUESTED** [review]
Please remove the log file. (logs/latest.log)

**Review by Max094Reikeb — APPROVED** [review]
Sounds good.

**Review by NOYBss — APPROVED** [review]
Looks good.

**Pull request merged**
