### PR TITLE
New splash screen background

### PR DESCRIPTION
**Pull request by ShockingArtist**
ui branch new splash, requested by max

### CODE REVIEW

**Comment by ShockingArtist** [comment]
Screen Shot 2020-12-05 at 2 06 35 PM

**Comment by Max094Reikeb** [comment]
Please change the destination branch to `MCToolkit:ui-update`

**Comment by Max094Reikeb** [comment]
You need to solve conflicts. You did not selected the right branch at first.

**Comment by Max094Reikeb** [comment]
Why did you close?

**Comment by ShockingArtist** [comment]
oopsies. on mobile. bad controls

**Comment by Max094Reikeb** [comment]
You just have to solve the conflict

**Comment by ShockingArtist** [comment]
i cant. im on mobile and it says its too advanced to be solved int he web version

**Comment by Max094Reikeb** [comment]
> i cant. im on mobile and it says its too advanced to be solved here

Well solve them when you will be on your computer...

**Comment by ShockingArtist** [comment]
uhh. i cant click on resolve conflicts, it still says its too complex

**Comment by ShockingArtist** [comment]
and since its an image, im not sure how I can remove the <<<<<<, >>>>>>, and ======

**Comment by Max094Reikeb** [comment]
> and since its an image, im not sure how I can remove the <<<<<<, >>>>>>, and ======

You might want to do another PR because you started the merge to the master branch, but the new splash screen will be effective in the UI update.

**Comment by ShockingArtist** [comment]
Closing

**Pull request closed without merging**
