### PR TITLE
Translated item description + shift-only and command-only description

### PR DESCRIPTION
**Pull request by Max094Reikeb**
This PR :
- Makes description automatically externalized (so, translatable)
- Adds a Shift-only description with checkbox
- Adds a Command-only/Control-only description with checkbox

It does the same as #12 but for items instead of blocks.

### CODE REVIEW

**Comment by Blackout03** [comment]
The item uses "block.testtwo.testitem."
even though the auto-generated one in the localization files is
"item.test_mod_two.test_item."
image
image

**Review by Goldorion — APPROVED** [review]

**Comment by Blackout03** [comment]
That's weird I am still getting the thing from my last comment (new workspace) and blocks are still not showing me any of the tooltips at all

**Comment by Max094Reikeb** [comment]
> That's weird I am still getting the thing from my last comment (new workspace) and blocks are still not showing me any of the tooltips at all

Try again, it should be fixed with my last commit...

**Review by Blackout03 — APPROVED** [review]
It works great now!

image
image

**Pull request merged**
