### PR TITLE
Support for blockstate variable/dependency type

### PR DESCRIPTION
**Pull request by AlsoSomeoneElse**
This PR adds support for blockstate variables (both local and global), dependencies, and "Return", "Call procedure and get return value", "Custom dependency" and "Get/Set variable" procedure blocks

### CODE REVIEW

**Comment by Max094Reikeb** [comment]
I just wonder how this work. How do you store a texture for a blockstate? For example a block that has a red texture and would turn green when redstone powered, how would you do that using your blockstate system?

**Comment by Goldorion** [comment]
You need to have a model file for each block state (and you add the model inside the block state file)

**Comment by AlsoSomeoneElse** [comment]
> 
> 
> I just wonder how this work. How do you store a texture for a blockstate? For example a block that has a red texture and would turn green when redstone powered, how would you do that using your blockstate system?

You can't, because it isn't what this PR is about. By blockstate variable, I mean something like this:
immagine
The variable stores the block and its state properties (for example its rotation, or its growth stage).

**Review by Goldorion — APPROVED** [review]

**Review by Max094Reikeb — CHANGES_REQUESTED** [review]
You need to merge master branch to yours to see if it still builds fine.

**Comment by AlsoSomeoneElse** [comment]
> 
> 
> You need to merge master branch to yours to see if it still builds fine.

I re-ran the checks and it builds fine now

**Comment by Max094Reikeb** [comment]
You should make the procedure block compatible with 1.16.4

**Review by Max094Reikeb — CHANGES_REQUESTED** [review]
Could you make those procedure blocks for 1.16.4 please?

**Comment by AlsoSomeoneElse** [comment]
Replaced this PR with #131

**Pull request closed without merging**
