### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ApposModding**

### CODE REVIEW

**Comment by Max094Reikeb** [comment]
No need to use a command to run the project. Configurations are here to help you.

**Comment by ApposModding** [comment]
Max, This is in the Idea terminal

**Comment by NOYBss** [comment]
Idea has a gradle sidebar which shows every task and allows you to run them, there is no need to use the terminal.

**Comment by Max094Reikeb** [comment]
> Idea has a gradle sidebar which shows every task and allows you to run them, there is no need to use the terminal.

Indeed, that's what I said. IntelliJ has an easier way to show you the pre-configurated tasks and you can just launch them with the play button.

**Pull request closed without merging**
