### PR TITLE
Improved GUI Editor

### PR DESCRIPTION
**Pull request by ShockingArtist**
guieditor

### CODE REVIEW

**Comment by NOYBss** [comment]
This is self-made right? (It looks like the original)

**Comment by ShockingArtist** [comment]
the original is hud-less

**Comment by NOYBss** [comment]
I mean the hud, it looks like the original minecraft hud

**Comment by ShockingArtist** [comment]
theyre taken from https://minecraft.gamepedia.com/Heads-up_display

**Comment by Max094Reikeb** [comment]
I don't get what's the difference...

**Comment by NOYBss** [comment]
> I don't get what's the difference...

the one we are using right now doesn't have bars



> theyre taken from https://minecraft.gamepedia.com/Heads-up_display

According to minecraft wiki's license we are good to use them as long as we give credit

**Comment by ShockingArtist** [comment]
I don't think credit is even needed, here's a quote from the license
>Within reason you're free to do whatever you want with screenshots and videos of the Game. By "within reason" we mean that you can't make any commercial use of them or do things that are unfair or adversely affect our rights unless we've specifically said it's okay in this EULA, allowed it through the Brand and Asset Usage Guidelines, or provided for it in a specific agreement with you. If you upload videos of the game to video sharing and streaming sites you are however allowed to put ads on them. Also, don't just rip art resources and pass them around, that's no fun.
but still, you should credit for safety

**Review by Max094Reikeb — APPROVED** [review]
Looks good for me

**Comment by titedog** [comment]
I agree, I think this is a needed change.

**Review by NOYBss — APPROVED** [review]

**Comment by Max094Reikeb** [comment]
2 approvals = merging...

**Pull request merged**
