### PR TITLE
New Redstone Emittion condition for Redstone Properties

### PR DESCRIPTION
**Pull request by Max094Reikeb**
This PR adds new Redstone emittion condition for the redstone properties.
It also adds Redstone properties code for 1.16.4 generator.

### CODE REVIEW

**Comment by NOYBss** [comment]
how about instead of a condition, making it return the amount of emitted redstone power, so blocks can emit different amount of redstone power according to whatever they want

**Comment by Goldorion** [comment]
> 
> 
> how about instead of a condition, making it return the amount of emitted redstone power, so blocks can emit different amount of redstone power according to whatever they want

It could also be both of them. It could have a condition to emit the redstone power and another thing to return the amount of emitted redstone power. Both of them can be usefull.

**Comment by KlemenDEV** [comment]
Would you mind adding this to 2021.1?

**Comment by AlsoSomeoneElse** [comment]
`Block#canProvidePower` only takes the blockstate as a parameter, so until blockstates are properly supported, this condition can't be added

**Comment by Max094Reikeb** [comment]
> Would you mind adding this to 2021.1?

Redstone properties has already been added to MCToolkit (check #1) so I don't think it would be useful.

> `Block#canProvidePower` only takes the blockstate as a parameter, so until blockstates are properly supported, this condition can't be added

I haven't tested yet but it builds fine so...

**Review by AlsoSomeoneElse — COMMENTED** [review]
> I haven't tested yet but it builds fine so...

It's because you added a BlockPos parameter, which makes it not override the method anymore. (I'm not sure why it counted this comment as a review)

**Comment by KlemenDEV** [comment]
> Redstone properties has already been added to MCToolkit (check #1) so I don't think it would be useful.

This PR was not merged back then due to lack of features in this PR. Either way, I may implement this then, as I did not think of adding this a condition way yet :D

**Comment by Max094Reikeb** [comment]
Anyways, I tested in-game, and it always emits redstone even if the procedure returns false.

**Comment by Goldorion** [comment]
I changed this PR to draft, so we won't it review and merge it before you fix the problem.

**Pull request merged**
