### PR TITLE
Custom pack maker tools for plugins

### PR DESCRIPTION
**Pull request by Goldorion**
This PR adds the possibility to create custom pack maker tools inside a plugin. Currently, only the wood pack maker and the tool pack maker tools have been moved to this new system. I will try to make a documentation later.

### CODE REVIEW

**Review by NOYBss — COMMENTED** [review]
Seems ok, except the changed jdk :)
In fact I didn't like the long switch case statement in CustomToolPackMaker, it's not really a problem, it's just a bit confusing
Maybe you could divide it into some other methods, a method for textures, items, blocks, recipes, tags

**Review by Max094Reikeb — CHANGES_REQUESTED** [review]
Change what @NOYBss said and commit to see if it build fine.

**Comment by Goldorion** [comment]
> 
> 
> Change what @NOYBss said and commit to see if it build fine.

Give me the time to make the changes ;)

**Review by Max094Reikeb — APPROVED** [review]
Looks good now. Waiting for a second approval to merge.

**Review by NOYBss — APPROVED** [review]

**Pull request merged**
