### PR TITLE
About 100 Modern Icons/Resources

### PR DESCRIPTION
**Pull request by ShockingArtist**
This PR is made for the purpose of providing some icons and resources, they'll seamlessly replace the current ones with cleaner, modern ones.
There are about 80 res files modified in total
These icons will be added as the first part of the Big UI/UX Update (before the revamp)

### CODE REVIEW

**Comment by ShockingArtist** [comment]
New suggested Input/output slot icons

**Comment by ShockingArtist** [comment]
7 new

**Comment by ShockingArtist** [comment]
6 extra icons were added

**Comment by Max094Reikeb** [comment]
Could you modify your first comment to show all the icons you modified please?

**Comment by ShockingArtist** [comment]
Check the resources zip
[resources copy.zip](https://github.com/Team-MCToolkit/MCToolkit/files/5583304/resources.copy.zip)

**Comment by ShockingArtist** [comment]
Added 17 new icons & resources included

**Comment by ShockingArtist** [comment]
Drafting this PR. Focusing on the concept UI/UX first and will be coming back

**Comment by ShockingArtist** [comment]
@Max094Reikeb Ready

**Comment by ShockingArtist** [comment]
Great!

**Pull request merged**
