### PR TITLE
Added 3 APIs to MCToolkit's core

### PR DESCRIPTION
**Pull request by Max094Reikeb**
This PR adds 3 APIs to MCToolkit's core.
The APIs are taken from the MCreator's plugin "More APIs support" : Curios, JEI and Patchouli.
The aim is not to automate everything, but at least to add them by default in MCToolkit.

### CODE REVIEW

**Comment by titedog** [comment]
Cool, cant wait to play around with these!

**Comment by Max094Reikeb** [comment]
> Cool, cant wait to play around with these!

Using APIs was already possible, for example if you wanted to have JEI inside your Minecraft client to test your recipes. The goal is to automate adding APIs. However, still in JEI example, there won't be automation for custom crafting recipe creation.

**Comment by titedog** [comment]
> 
> 
> > Cool, cant wait to play around with these!
> 
> Using APIs was already possible, for example if you wanted to have JEI inside your Minecraft client to test your recipes. The goal is to automate adding APIs. However, still in JEI example, there won't be automation for custom crafting recipe creation.

I already knew this I was just happy since it would be a little easier to implement

**Comment by Max094Reikeb** [comment]
This PR has been set to draft until Curios API works with Minecraft 1.16.4.

**Pull request merged**
