### PR TITLE
MacOSX Patch

### PR DESCRIPTION
**Pull request by ApposModding**

### CODE REVIEW

**Comment by Max094Reikeb** [comment]
You're saying it's a Patch, but what does it fix?

**Comment by Goldorion** [comment]
> You're saying it's a Patch, but what does it fix?

It change the name of the mcreator.jar for mctoolkit.jar, but I don't remember if I changed it in the Mac versions.

**Comment by ApposModding** [comment]
yes you did

**Comment by ApposModding** [comment]
i checked

**Comment by Max094Reikeb** [comment]
> yes you did

Could you show me where?

**Comment by TeamRIS** [comment]
this is my alt account

**Comment by Max094Reikeb** [comment]
> this is my alt account

?

**Pull request closed without merging**
