### PR TITLE
Move potion items in a new mod element

### PR DESCRIPTION
**Pull request by Goldorion**
This PR adds a new mod element named Potion Item. This new mod element adds the possibility to create custom potions with more parameters. Custom and vanilla effects can be used in the same custom potion. The duration and the amplifier (potion level) can also be changed. A screen of the UI can be found [here](https://i.imgur.com/05oV3gG.png).

Note: Potions of custom effects will have to be re-created.

Edit: This PR also changes the copyright texts (when we create new files).

### CODE REVIEW

**Review by ShockingArtist — APPROVED** [review]

**Comment by ShockingArtist** [comment]
Looks pretty neat

**Review by Max094Reikeb — APPROVED** [review]
Seems good!

**Comment by Goldorion** [comment]
I forgot to add the tests :/

**Comment by Max094Reikeb** [comment]
> I forgot to add the tests :/

Indeed, I forgot there were tests too... Could you also test when you delete your potions that all translation keys delete successfully?

**Pull request merged**
